POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer xxx

{
    "author": "Testi Jäbä",
    "title": "Baby's first blog post",
    "url": "https://example.com",
    "likes": "100",
    "userId": ""
}